# ITEM_INFO 테이블
# ITEM_TREE 테이블

SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME FROM ITEM_INFO, ITEM_TREE
WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID
    AND ITEM_TREE.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_INFO.ITEM_ID ASC