# ECOLI_DATA 테이블

SELECT 
    ECOLI_DATA.ID AS ID, 
    IFNULL(PARENT_CHILD.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA
LEFT JOIN (
    SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS PARENT_CHILD
ON ECOLI_DATA.ID = PARENT_CHILD.PARENT_ID
ORDER BY ID ASC
