# CAR_RENTAL_COMPANY_CAR 테이블
# CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블

# 1. 종류는 세단 or SUV
# 2. 2022.11.1 ~ 2022.11.30에 대여기록이 없어야함
# 3. 30일간의 대여금액이 50만원 이상 200만원 미만

WITH SEDAN_SUV_INFO AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV'
),
RENTAL_NOT_OK AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE ('2022-11-01' <= START_DATE AND START_DATE <= '2022-11-30')
            OR ('2022-11-01' <= END_DATE AND END_DATE <= '2022-11-30')
            OR (START_DATE <= '2022-11-01' AND '2022-11-30' <= END_DATE)
),
SEDAN_SUV_RENTAL_OK AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM SEDAN_SUV_INFO
    WHERE SEDAN_SUV_INFO.CAR_ID NOT IN (SELECT CAR_ID FROM RENTAL_NOT_OK)
),
CAR_30DAY_RENTAL AS (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
),
FINAL AS (
    SELECT SEDAN_SUV_RENTAL_OK.CAR_ID, 
            SEDAN_SUV_RENTAL_OK.CAR_TYPE,
            ROUND(SEDAN_SUV_RENTAL_OK.DAILY_FEE * ((100 - CAR_30DAY_RENTAL.DISCOUNT_RATE) / 100) * 30, 0) AS FEE
    FROM SEDAN_SUV_RENTAL_OK, CAR_30DAY_RENTAL
    WHERE SEDAN_SUV_RENTAL_OK.CAR_TYPE = CAR_30DAY_RENTAL.CAR_TYPE
)

SELECT * FROM FINAL
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC