# REST_INFO 테이블
# REST_REVIEW 테이블

# SELECT * FROM REST_INFO
# SELECT * FROM REST_REVIEW


SELECT REST_INFO.REST_ID,
        REST_INFO.REST_NAME,
        REST_INFO.FOOD_TYPE,
        REST_INFO.FAVORITES,
        REST_INFO.ADDRESS,
        REST_REVIEW.SCORE
FROM (
    SELECT *
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) AS REST_INFO
JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS REST_REVIEW
ON REST_REVIEW.REST_ID = REST_INFO.REST_ID
ORDER BY REST_REVIEW.SCORE DESC, REST_INFO.FAVORITES DESC