# USER_INFO
# ONLINE_SALE

SELECT 
    USER_SALES.YEAR_SALES AS YEAR,
    USER_SALES.MONTH_SALES AS MONTH,
    USER_GENDER.GENDER AS GENDER,
    COUNT(*) AS USERS
FROM (
    SELECT DISTINCT 
        USER_ID, 
        YEAR(SALES_DATE) AS YEAR_SALES, 
        MONTH(SALES_DATE) AS MONTH_SALES
    FROM ONLINE_SALE
) AS USER_SALES
JOIN (
    SELECT USER_ID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) AS USER_GENDER
ON USER_SALES.USER_ID = USER_GENDER.USER_ID
GROUP BY USER_SALES.YEAR_SALES, USER_SALES.MONTH_SALES, USER_GENDER.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC