SELECT COUNT(*) AS FISH_COUNT, FISH_NAME_INFO.FISH_NAME AS FISH_NAME
FROM FISH_NAME_INFO
JOIN FISH_INFO ON FISH_NAME_INFO.FISH_TYPE = FISH_INFO.FISH_TYPE
GROUP BY FISH_INFO.FISH_TYPE, FISH_NAME_INFO.FISH_NAME
ORDER BY FISH_COUNT DESC