# CAR_RENTAL_COMPANY_RENTAL_HISTORY

SELECT CAR.CAR_ID, IFNULL(ING.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
    ) AS CAR
LEFT JOIN (
        SELECT CAR_ID, '대여중' AS AVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
        GROUP BY CAR_ID
    ) AS ING
ON CAR.CAR_ID = ING.CAR_ID
ORDER BY CAR_ID DESC



