# ANIMAL_INS 테이블
# ANIMAL_OUTS 테이블

SELECT A_I.NAME, A_I.DATETIME
FROM ANIMAL_INS A_I
LEFT JOIN ANIMAL_OUTS A_O
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_O.ANIMAL_ID is NULL
ORDER BY A_I.DATETIME
LIMIT 3