# CAR_RENTAL_COMPANY_CAR
# CAR_RENTAL_COMPANY_RENTAL_HISTORY
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN

WITH HISTORY AS (
    SELECT CAR_RENTAL_COMPANY_RENTAL_HISTORY.HISTORY_ID, 
            CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID, 
            TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 AS DURATION,
            CASE
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90
                THEN 90
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 BETWEEN 30 AND 89
                THEN 30
                WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 BETWEEN 7 AND 29
                THEN 7
                ELSE 0
            END AS DURATION_TYPE,
            CAR_RENTAL_COMPANY_CAR.DAILY_FEE  
    FROM CAR_RENTAL_COMPANY_CAR, CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_RENTAL_COMPANY_CAR.CAR_ID = CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID
            AND CAR_RENTAL_COMPANY_CAR.CAR_TYPE = '트럭'
),
TRUCK_DURATION_DISCOUNT AS (
    SELECT REPLACE(SUBSTRING_INDEX(DURATION_TYPE, ' ', 1), '일', '') AS DURATION_TYPE,
            DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
),
FINAL_INFO AS (
    SELECT 
        HISTORY.HISTORY_ID, 
        HISTORY.DURATION * HISTORY.DAILY_FEE AS FEE,
        IFNULL(TRUCK_DURATION_DISCOUNT.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM HISTORY
    LEFT JOIN TRUCK_DURATION_DISCOUNT
    ON HISTORY.DURATION_TYPE = TRUCK_DURATION_DISCOUNT.DURATION_TYPE
)

SELECT HISTORY_ID,
        ROUND(FEE * ((100 - DISCOUNT_RATE) / 100)) AS FEE
FROM FINAL_INFO
ORDER BY FEE DESC, HISTORY_ID DESC



# SELECT HISTORY.HISTORY_ID,
#         CASE
#             WHEN HISTORY.DURATION BETWEEN 0 AND 6
#             THEN HISTORY.DAILY_FEE * ((100 - TRUCK_DURATION_DISCOUNT.DISCOUNT_RATE) / 100)
#             ELSE
#         END AS FEE
# FROM HISTORY, TRUCK_DURATION_DISCOUNT
# SELECT * FROM TRUCK_DURATION_DISCOUNT