# FIRST_HALF 테이블
# JULY 테이블

# SELECT * FROM FIRST_HALF
# SELECT * FROM JULY

SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF, JULY
WHERE FIRST_HALF.FLAVOR = JULY.FLAVOR
GROUP BY JULY.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER + SUM(JULY.TOTAL_ORDER) DESC
LIMIT 3
