# ANIMAL_OUTS 테이블

WITH RECURSIVE cte (HOUR) AS
(
    SELECT 0
    UNION
    SELECT HOUR + 1 FROM cte WHERE HOUR < 23
)

SELECT cte.HOUR, IFNULL(EXIST_TABLE.COUNT, 0) AS COUNT
FROM cte
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR,
        COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR
) AS EXIST_TABLE
ON cte.HOUR = EXIST_TABLE.HOUR
ORDER BY HOUR ASC