# USED_GOODS_BOARD 테이블
# USED_GOODS_USER 테이블

SELECT USED_GOODS_USER.USER_ID, 
        USED_GOODS_USER.NICKNAME, 
        USER_TOTAL_PRICE.TOTAL_PRICE AS TOTAL_SALES
FROM USED_GOODS_USER
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_PRICE >= 700000
) AS USER_TOTAL_PRICE
ON USED_GOODS_USER.USER_ID = USER_TOTAL_PRICE.WRITER_ID
ORDER BY TOTAL_SALES ASC




