# ITEM_INFO 테이블
# ITEM_TREE 테이블

SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO
JOIN (
    SELECT ITEM_TREE.ITEM_ID AS NEXT_ID
    FROM ITEM_INFO
    LEFT JOIN ITEM_TREE
    ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
        AND ITEM_INFO.RARITY = 'RARE'
    WHERE ITEM_TREE.ITEM_ID IS NOT NULL
) AS NEW_TABLE
ON ITEM_INFO.ITEM_ID = NEW_TABLE.NEXT_ID
ORDER BY ITEM_INFO.ITEM_ID DESC
