# ECOLI_DATA

WITH ID_GENOTYPE AS (
    SELECT ID, GENOTYPE
    FROM ECOLI_DATA
),
PARENT_MATCH AS (
    SELECT ECOLI_DATA.ID, 
            ECOLI_DATA.GENOTYPE, 
            ECOLI_DATA.PARENT_ID,
            ID_GENOTYPE.GENOTYPE AS PARENT_GENOTYPE
    FROM ECOLI_DATA
    LEFT JOIN ID_GENOTYPE
    ON ECOLI_DATA.PARENT_ID = ID_GENOTYPE.ID
)


SELECT ID, GENOTYPE, PARENT_GENOTYPE
FROM PARENT_MATCH
WHERE (GENOTYPE & PARENT_GENOTYPE) = PARENT_GENOTYPE
ORDER BY ID