# FISH_INFO 테이블
# FISH_NAME_INFO 테이블

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO, FISH_NAME_INFO
WHERE FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
    AND (FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER')