# HR_DEPARTMENT 테이블
# HR_EMPLOYEES 테이블
# HR_GRADE 테이블

SELECT 
    SUM(HR_GRADE.SCORE) AS SCORE,
    HR_EMPLOYEES.EMP_NO, 
    HR_EMPLOYEES.EMP_NAME,
    HR_EMPLOYEES.POSITION,
    HR_EMPLOYEES.EMAIL
FROM HR_EMPLOYEES, HR_GRADE
WHERE HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
GROUP BY HR_GRADE.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
