# USED_GOODS_BOARD 테이블
# USED_GOODS_FILE 테이블

# 조회수가 가장 높은 중고거래 게시물
WITH HIGH_BOARD_TABLE AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (
                    SELECT MAX(VIEWS) FROM USED_GOODS_BOARD
                )
),
HIGH_BOARD_FILE AS (
    SELECT USED_GOODS_FILE.FILE_ID, 
            USED_GOODS_FILE.FILE_EXT, 
            USED_GOODS_FILE.FILE_NAME, 
            USED_GOODS_FILE.BOARD_ID
    FROM USED_GOODS_FILE, HIGH_BOARD_TABLE
    WHERE HIGH_BOARD_TABLE.BOARD_ID = USED_GOODS_FILE.BOARD_ID
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM HIGH_BOARD_FILE
ORDER BY FILE_ID DESC