# BOOK 테이블
# BOOK_SALES 테이블


SELECT CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM (
        SELECT 
            BOOK.BOOK_ID AS BOOK_ID,
            BOOK.CATEGORY AS CATEGORY,
            SALES_CNT.TOTAL_SALES AS TOTAL_SALES
        FROM BOOK, (
                SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
                FROM BOOK_SALES
                WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
                GROUP BY BOOK_ID
            ) AS SALES_CNT
        WHERE BOOK.BOOK_ID = SALES_CNT.BOOK_ID
    ) AS BOOK_SALES_CNT
GROUP BY BOOK_SALES_CNT.CATEGORY
ORDER BY BOOK_SALES_CNT.CATEGORY ASC

